# Data Health Audit

## Important Note

This notebook `/notebooks/3_data_health_audit_global_only.ipynb` is different than the sub-sampled version `/notebooks/3_data_health_audit_sample_only.ipynb` in terms of structure and purpose. 

Purpose: The sub-sampled version aims to check the data health and explore potential issue in various aspect of the dataset. This one aims to verify if the issues/trend/patterns found in the sub-sampled counterpart will be similar to this version. The similar pattern exhibits from two notebooks will indirectly indicates that the subsampling strategy is unbiased and effective, and vice versa.

Structure: The subsampled version will explicitly write down the logic as you audit the data health, whereas this version will put most workflows in `/src/utils/data_health_audit_helper.py`, and the audit logic will call a specific function to perform and verify health check.

## Import Modules

In [1]:
from pathlib import Path
import sys
import os

In [2]:
## Use for import external directory modules
# Make sure you are the parent directory
# Define directory path: notebooks/ -> project root
PROJECT_ROOT = Path.cwd().resolve().parent
display(PROJECT_ROOT)

# Add it to sys.path
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

PosixPath('/expanse/lustre/projects/uci157/bguo3/DSC_288R')

In [3]:
# Other libs
from src.utils.pyspark_helper import (
    create_spark_session, 
    memory_count
)
from src.utils.data_health_audit_helper import (
    structure_report,
    schema_audit,
    null_report,
    consistency_report,
    validity_report,
    anomaly_report,
    noise_report,
    uniqueness_report,
    duplicate_report,
    print_section,
    format_report
)

Matplotlib created a temporary cache directory at /scratch/bguo3/job_48715834/matplotlib-x68xymia because the default path (/home/jovyan/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.

## Set up for Spark

In [4]:
# Set up a dedicated job-running spill storage directory
SPARK_LOCAL_DIR = f"/scratch/{os.environ['USER']}/job_{os.environ['SLURM_JOB_ID']}/spark-local"
os.makedirs(SPARK_LOCAL_DIR, exist_ok=True)

# Set up for Spark app & resource allocation
spark = create_spark_session(
    "steam_reviews_data_health_audit", 
    extra_configs={
        "spark.local.dir": SPARK_LOCAL_DIR
    }
)
print(spark.conf.get("spark.local.dir"))

/scratch/bguo3/job_48715834/spark-local

## Define Paths & Read Full Data Parquet File

In [5]:
# -----------------------------
# Paths
# -----------------------------
EXPANSE_ROOT = "/expanse/lustre/scratch/bguo3/temp_project"
FULL_PARQUET_PATH = f"file:{EXPANSE_ROOT}/steam_reviews/full_parquet"

df = spark.read.parquet(FULL_PARQUET_PATH)
print(f"Read full parquet successfully from: {FULL_PARQUET_PATH}")

Read full parquet successfully from: file:/expanse/lustre/scratch/bguo3/temp_project/steam_reviews/full_parquet

## Dataset Structure

In [6]:
ROW_COUNT = df.count()

## Shape
# 1. (# of rows, # of columns, # of cells)
print_section("1. (# of rows, # of columns, # of cells)")
display(structure_report(df, ROW_COUNT))

## 2. Concise summary on columns details
print_section("2. Concise summary on columns details")
display(schema_audit(df))
df.printSchema()

# 3. Memory count
print_section("3. Memory count")
memory_count(df)

======================================================================
1. (# of rows, # of columns, # of cells)
======================================================================

   row_count  column_count  cell_count
0  113885601            18  2049940818

======================================================================
2. Concise summary on columns details
======================================================================

,column_name,present_in_df,expected_type,actual_type,matches_expected_family
0,author_steamid,True,bigint,bigint,True
1,appid,True,int,int,True
2,author_num_games_owned,True,int,int,True
3,author_num_reviews,True,int,int,True
4,author_playtime_forever,True,int,int,True
5,author_playtime_last_two_weeks,True,int,int,True
6,author_playtime_at_review,True,int,int,True
7,author_last_played,True,bigint,bigint,True
8,review,True,string,string,True
9,voted_up,True,boolean,boolean,True
10,votes_up,True,int,int,True
11,votes_funny,True,bigint,bigint,True
12,weighted_vote_score,True,float,float,True
13,comment_count,True,int,int,True
14,written_during_early_access,True,boolean,boolean,True
15,timestamp_created,True,bigint,bigint,True
16,timestamp_updated,True,bigint,bigint,True
17,language,True,string,string,True

root
 |-- author_steamid: long (nullable = true)
 |-- appid: integer (nullable = true)
 |-- author_num_games_owned: integer (nullable = true)
 |-- author_num_reviews: integer (nullable = true)
 |-- author_playtime_forever: integer (nullable = true)
 |-- author_playtime_last_two_weeks: integer (nullable = true)
 |-- author_playtime_at_review: integer (nullable = true)
 |-- author_last_played: long (nullable = true)
 |-- review: string (nullable = true)
 |-- voted_up: boolean (nullable = true)
 |-- votes_up: integer (nullable = true)
 |-- votes_funny: long (nullable = true)
 |-- weighted_vote_score: float (nullable = true)
 |-- comment_count: integer (nullable = true)
 |-- written_during_early_access: boolean (nullable = true)
 |-- language: string (nullable = true)
 |-- timestamp_created: long (nullable = true)
 |-- timestamp_updated: long (nullable = true)


======================================================================
3. Memory count
======================================================================
Total estimated size: 55.74 GB

## Completeness

In [9]:
## Compeleteness helps us investigate missing value and if we have useful
## features for prediction problems

# 1. Identify missing values per column
# 2. Calculate percentage of missing values
null_report(df, ROW_COUNT).show(truncate=False)

+------------------------------+----------+---------+---------------------+
|column_name                   |null_count|row_count|null_rate            |
+------------------------------+----------+---------+---------------------+
|voted_up                      |2956554   |113885601|0.02596073580891056  |
|timestamp_created             |2955600   |113885601|0.02595235898171183  |
|timestamp_updated             |2414900   |113885601|0.021204612161637538 |
|votes_up                      |1772064   |113885601|0.015560035548304303 |
|votes_funny                   |1554643   |113885601|0.013650917994453048 |
|written_during_early_access   |1423070   |113885601|0.012495609519591507 |
|weighted_vote_score           |1378404   |113885601|0.012103408928754743 |
|comment_count                 |1233750   |113885601|0.010833239576968119 |
|author_steamid                |1878      |113885601|1.649023215849737E-5 |
|author_num_games_owned        |1860      |113885601|1.6332178815125188E-5|
|author_num_reviews            |1752      |113885601|1.5383858754892112E-5|
|appid                         |1291      |113885601|1.1335937016304634E-5|
|author_playtime_forever       |1149      |113885601|1.0089071751924109E-5|
|author_playtime_last_two_weeks|1148      |113885601|1.0080291010625653E-5|
|author_last_played            |1143      |113885601|1.0036387304133382E-5|
|author_playtime_at_review     |1138      |113885601|9.99248359764111E-6  |
|review                        |1129      |113885601|9.91345692595502E-6  |
|language                      |1129      |113885601|9.91345692595502E-6  |
+------------------------------+----------+---------+---------------------+

## Consistency & Validity

In [10]:
## Consistency helps us question "Do columns agree with each other logically"?

# 1. timestamp_created should usually be <= timestamp_updated
# 2. playtime_at_review & playtime_last two weeks should be less than lifetime playtime
# 3. all user in the dataset should have at least 1 numbers of review
# 4. author_playtime_forever at later review time should not be lower than earlier review time
format_report(consistency_report(df, ROW_COUNT))

======================================================================
timestamp_created_gt_timestamp_updated
======================================================================
Violation count: 67
Violation percentage: 5.88309666996445e-07
Showing first 10 rows:
+-----------------+-------+-----------------+-----------------+
|author_steamid   |appid  |timestamp_created|timestamp_updated|
+-----------------+-------+-----------------+-----------------+
|76561198059619745|281990 |4                |3                |
|1590801716       |NULL   |1                |0                |
|76561199124521359|686810 |2                |1                |
|76561198010909133|906100 |2                |1                |
|NULL             |NULL   |1                |0                |
|76561198050620715|931690 |1559566943       |1559566933       |
|76561198004160508|1063730|2                |1                |
|76561198021406864|1250410|200              |100              |
|76561198116916435|1255630|18               |17               |
|76561198367452421|314160 |40               |30               |
+-----------------+-------+-----------------+-----------------+
only showing top 10 rows


======================================================================
author_playtime_at_review_gt_author_playtime_forever
======================================================================
Violation count: 45741
Violation percentage: 0.00040163988773260284
Showing first 10 rows:
+-----------------+-----+-------------------------+-----------------------+-----------------+
|author_steamid   |appid|author_playtime_at_review|author_playtime_forever|timestamp_created|
+-----------------+-----+-------------------------+-----------------------+-----------------+
|76561198211357228|2820 |5004                     |5003                   |1623757205       |
|76561198047884173|2820 |2838                     |2795                   |1542907547       |
|76561197970524059|2820 |11365                    |11106                  |1511501361       |
|76561198032917633|2820 |5871                     |5823                   |1480089818       |
|76561198014174000|2820 |8499                     |7945                   |1425203189       |
|76561197962867976|2820 |4833                     |4321                   |1403745768       |
|76561198017666466|2820 |17737                    |17289                  |NULL             |
|76561197994049999|2820 |23827                    |23696                  |1391736057       |
|76561198060348462|2820 |12744                    |12738                  |1378331536       |
|76561198014670806|2820 |5309                     |5005                   |1366839394       |
+-----------------+-----+-------------------------+-----------------------+-----------------+
only showing top 10 rows


======================================================================
author_playtime_last_two_weeks_gt_author_playtime_forever
======================================================================
Violation count: 6417
Violation percentage: 5.63460169121819e-05
Showing first 10 rows:
+-----------------+------+------------------------------+-----------------------+-----------------+
|author_steamid   |appid |author_playtime_last_two_weeks|author_playtime_forever|timestamp_created|
+-----------------+------+------------------------------+-----------------------+-----------------+
|76561199558774627|281990|2564                          |2562                   |1698490671       |
|76561198041079718|282140|476                           |436                    |1698248043       |
|76561199040430973|367520|3209                          |3208                   |1698857767       |
|76561199466596055|367520|581                           |562                    |1698850735       |
|76561199215876536|367520|1352                          |1345                   |1698840363       |
|76561199439235195|367520|3922                          |3902                   |1698835071       |
|76561199103485556|367520|606                           |605                    |1698920461       |
|76561197995358854|368230|8                             |7                      |1697967301       |
|76561198328602668|368260|1378                          |1369                   |1697966481       |
|76561199481104818|368360|2964                          |2960                   |1698320779       |
+-----------------+------+------------------------------+-----------------------+-----------------+
only showing top 10 rows


======================================================================
users_with_min_author_num_reviews_eq_0
======================================================================
Violation count: 57
Violation percentage: 1.503219778089422e-06
Showing first 10 rows:
+--------------+----------------------+
|author_steamid|min_author_num_reviews|
+--------------+----------------------+
|1401192537    |0                     |
|1343318492    |0                     |
|1299504642    |0                     |
|1309736445    |0                     |
|1302726090    |0                     |
|1356046511    |0                     |
|1292262085    |0                     |
|1334083245    |0                     |
|1388369867    |0                     |
|1325023197    |0                     |
+--------------+----------------------+
only showing top 10 rows


======================================================================
author_playtime_forever_decreases_over_time
======================================================================
Violation count: 1
Violation percentage: 8.780741298454403e-09
Showing first 10 rows:
+-----------------+-----+-----------------+-----------------------+---------------------+
|author_steamid   |appid|timestamp_created|author_playtime_forever|prev_playtime_forever|
+-----------------+-----+-----------------+-----------------------+---------------------+
|76561198169949761|730  |1480413221       |208966                 |209002               |
+-----------------+-----+-----------------+-----------------------+---------------------+

In [8]:
## Validity helps us question "Do columns within reasonable range"?

# 5. Count-like columns should not be negative
# 6. weighted_vote_score should be between 0 and 1
format_report(validity_report(df, ROW_COUNT))

======================================================================
author_num_games_owned_negative
======================================================================
Violation count: 0
Violation percentage: 0.0
Showing first 10 rows:
+--------------+-----+----------------------+-----------------+
|author_steamid|appid|author_num_games_owned|timestamp_created|
+--------------+-----+----------------------+-----------------+
+--------------+-----+----------------------+-----------------+


======================================================================
author_num_reviews_negative
======================================================================
Violation count: 0
Violation percentage: 0.0
Showing first 10 rows:
+--------------+-----+------------------+-----------------+
|author_steamid|appid|author_num_reviews|timestamp_created|
+--------------+-----+------------------+-----------------+
+--------------+-----+------------------+-----------------+


======================================================================
author_playtime_forever_negative
======================================================================
Violation count: 0
Violation percentage: 0.0
Showing first 10 rows:
+--------------+-----+-----------------------+-----------------+
|author_steamid|appid|author_playtime_forever|timestamp_created|
+--------------+-----+-----------------------+-----------------+
+--------------+-----+-----------------------+-----------------+


======================================================================
author_playtime_last_two_weeks_negative
======================================================================
Violation count: 0
Violation percentage: 0.0
Showing first 10 rows:
+--------------+-----+------------------------------+-----------------+
|author_steamid|appid|author_playtime_last_two_weeks|timestamp_created|
+--------------+-----+------------------------------+-----------------+
+--------------+-----+------------------------------+-----------------+


======================================================================
author_playtime_at_review_negative
======================================================================
Violation count: 0
Violation percentage: 0.0
Showing first 10 rows:
+--------------+-----+-------------------------+-----------------+
|author_steamid|appid|author_playtime_at_review|timestamp_created|
+--------------+-----+-------------------------+-----------------+
+--------------+-----+-------------------------+-----------------+


======================================================================
votes_up_negative
======================================================================
Violation count: 4
Violation percentage: 3.512296519381761e-08
Showing first 10 rows:
+-----------------+------+--------+-----------------+
|author_steamid   |appid |votes_up|timestamp_created|
+-----------------+------+--------+-----------------+
|76561198277370402|323190|-50     |NULL             |
|76561198127860956|397160|-2016   |NULL             |
|76561198254386447|443110|-1      |NULL             |
|76561199447445925|700330|-19     |NULL             |
+-----------------+------+--------+-----------------+


======================================================================
votes_funny_negative
======================================================================
Violation count: 3
Violation percentage: 2.6342223895363208e-08
Showing first 10 rows:
+-----------------+------+-----------+-----------------+
|author_steamid   |appid |votes_funny|timestamp_created|
+-----------------+------+-----------+-----------------+
|76561198254386447|443110|-1         |NULL             |
|76561197975280632|286040|-3         |NULL             |
|76561199447445925|700330|-53        |NULL             |
+-----------------+------+-----------+-----------------+


======================================================================
comment_count_negative
======================================================================
Violation count: 3
Violation percentage: 2.6342223895363208e-08
Showing first 10 rows:
+-----------------+------+-------------+-----------------+
|author_steamid   |appid |comment_count|timestamp_created|
+-----------------+------+-------------+-----------------+
|76561198115231461|578650|-2           |NULL             |
|76561199447445925|700330|-96          |NULL             |
|76561198040545746|445220|-1           |NULL             |
+-----------------+------+-------------+-----------------+


======================================================================
weighted_vote_score_out_of_range
======================================================================
Violation count: 568938
Violation percentage: 0.004995697392860051
Showing first 10 rows:
+-----------------+------+-------------------+-----------------+
|author_steamid   |appid |weighted_vote_score|timestamp_created|
+-----------------+------+-------------------+-----------------+
|76561198039387092|281990|1.53171546E9       |NULL             |
|76561198034884692|281990|1.54774515E9       |NULL             |
|76561198044364514|281990|1.53031232E9       |NULL             |
|76561198039016183|281990|5.0                |NULL             |
|76561198119801514|281990|45.0               |NULL             |
|76561198178547762|281990|7.0                |NULL             |
|76561198128373543|281990|1.52967373E9       |NULL             |
|76561197976411770|281990|1.52963379E9       |NULL             |
|76561197973366094|281990|1.52946918E9       |NULL             |
|76561198026673857|281990|29.0               |NULL             |
+-----------------+------+-------------------+-----------------+
only showing top 10 rows

## Anomaly & Outliers

In [12]:
## Anomaly indicates suspicious value, not automatically wrong
ano_report = anomaly_report(df, ROW_COUNT)

# 1. Check for outlier value using summary statistics
display(ano_report.get('numeric_describe_df').toPandas())

# 2. Create report regarding anomaly report for suspicious features (1) votes_funny artifact
# 3. Check for instances where votes_funny reached max value
# 4. Check for instances where votes_funny near max value
format_report(ano_report)

# 5. Find the largest vote_funny value that follows right after ARTIFACT_THRESHOLD, compute its propoertion comparing to max value
# If it's between 60% - 95%, it will indicate broader range of artifact from API and we will need to dive deeper
print_section("Largest non-artifact votes_funny value below threshold")
ano_value, ano_percentage = ano_report.get('vote_max_non_artifact', (None, None))
if ano_value is not None: print(ano_value)
if ano_percentage is not None: print(ano_percentage)
del ano_report, ano_value, ano_percentage

,summary,author_num_games_owned,author_num_reviews,author_playtime_forever,author_playtime_last_two_weeks,author_playtime_at_review,votes_up,votes_funny,comment_count,weighted_vote_score
0,count,113883741,113883849,113884452,113884453,113884463,112113537,112330958,112651851,112507197
1,mean,833.5436838169902,399.9623533447662,15573.124560111155,116.18008222772954,7129.382843241751,8997958.327789998,6953203.962033075,4467856.069244153,NaN
2,stddev,981228.2934024984,715900.9208064852,496019.5376433794,218722.14813122991,227509.99698184888,1.1864653059586446E8,1.052227155457046E8,8.369630425056835E7,NaN
3,min,0,0,0,0,0,-2016,-53,-96,-89.0
4,max,1651393883,1651393883,1403342723,1393862250,1402630204,1699017189,4294967295,1699015475,NaN

======================================================================
playtime_2w_near_limit
======================================================================
Violation count: 16632
Violation percentage: 0.00014604128927589362
Showing first 10 rows:
+-----------------+------+------------------------------+-----------------------+-----------------+
|author_steamid   |appid |author_playtime_last_two_weeks|author_playtime_forever|timestamp_created|
+-----------------+------+------------------------------+-----------------------+-----------------+
|NULL             |NULL  |1393862250                    |1393862250             |0                |
|NULL             |NULL  |1356627477                    |NULL                   |0                |
|NULL             |NULL  |1290286146                    |1290286146             |0                |
|76561199529253953|730   |112370                        |105504                 |1692376470       |
|76561199404792985|730   |56748                         |203490                 |1666940962       |
|76561199488329913|730   |45285                         |114381                 |1691684617       |
|76561199013645279|730   |41953                         |81887                  |1603308881       |
|76561199177996816|730   |36370                         |181325                 |1626262465       |
|76561198315604942|431960|33369                         |296485                 |1673236213       |
|76561198844172674|730   |33012                         |625390                 |1580385222       |
+-----------------+------+------------------------------+-----------------------+-----------------+
only showing top 10 rows


======================================================================
playtime_2w_exceeds_limit
======================================================================
Violation count: 17
Violation percentage: 1.4927260207372485e-07
Showing first 10 rows:
+-----------------+------+------------------------------+-----------------------+-----------------+
|author_steamid   |appid |author_playtime_last_two_weeks|author_playtime_forever|timestamp_created|
+-----------------+------+------------------------------+-----------------------+-----------------+
|NULL             |NULL  |1393862250                    |1393862250             |0                |
|NULL             |NULL  |1356627477                    |NULL                   |0                |
|NULL             |NULL  |1290286146                    |1290286146             |0                |
|76561199529253953|730   |112370                        |105504                 |1692376470       |
|76561199404792985|730   |56748                         |203490                 |1666940962       |
|76561199488329913|730   |45285                         |114381                 |1691684617       |
|76561199013645279|730   |41953                         |81887                  |1603308881       |
|76561199177996816|730   |36370                         |181325                 |1626262465       |
|76561198315604942|431960|33369                         |296485                 |1673236213       |
|76561198844172674|730   |33012                         |625390                 |1580385222       |
+-----------------+------+------------------------------+-----------------------+-----------------+
only showing top 10 rows


======================================================================
votes_funny_is_uint32_artifact
======================================================================
Violation count: 1797
Violation percentage: 1.577899211332256e-05
Showing first 10 rows:
+-----------------+-----+-----------+--------+-------------------+-------------+-----------------+
|author_steamid   |appid|votes_funny|votes_up|weighted_vote_score|comment_count|timestamp_created|
+-----------------+-----+-----------+--------+-------------------+-------------+-----------------+
|76561198077137629|95400|4294967295 |1       |0.50248754         |2            |1498924420       |
|76561198373834172|730  |4294967295 |3       |0.5497954          |0            |1491126049       |
|76561198162957462|730  |4294967295 |4       |0.5318596          |0            |1464021758       |
|76561198348454517|730  |4294967295 |2       |0.5217391          |1            |1491056634       |
|76561198107469575|730  |4294967295 |1       |0.5                |0            |1438509941       |
|76561197960572548|730  |4294967295 |1       |0.50248754         |0            |1490927311       |
|76561198093231351|730  |4294967295 |2       |0.54545456         |2            |1458027221       |
|76561198115233393|730  |4294967295 |1       |0.51008064         |0            |1490860377       |
|76561198358264899|730  |4294967295 |1       |0.52380955         |2            |1499032866       |
|76561198251991710|730  |4294967295 |0       |0.47826087         |0            |1490834417       |
+-----------------+-----+-----------+--------+-------------------+-------------+-----------------+
only showing top 10 rows


======================================================================
votes_funny_near_exact_uint32_artifact_max
======================================================================
Violation count: 286
Violation percentage: 2.511292011357959e-06
Showing first 10 rows:
+-----------------+------+-----------+--------+-------------------+-------------+-----------------+
|author_steamid   |appid |votes_funny|votes_up|weighted_vote_score|comment_count|timestamp_created|
+-----------------+------+-----------+--------+-------------------+-------------+-----------------+
|76561198175843007|281990|4294967294 |7       |0.3812853          |0            |1491921485       |
|76561198295625369|730   |4294967294 |1       |0.5                |0            |1470399079       |
|76561198367846181|730   |4294967294 |1       |0.50248754         |0            |1489136497       |
|76561198013659280|730   |4294967294 |0       |0.49751243         |0            |1459714431       |
|76561198194611958|730   |4294967294 |2       |0.5051732          |0            |1447086848       |
|76561198202420464|730   |4294967294 |0       |0.4352899          |0            |1456659200       |
|76561198299361521|730   |4294967294 |2       |0.5049505          |0            |1489063424       |
|76561198262527789|730   |4294967294 |0       |0.49751243         |0            |1454968806       |
|76561198147344241|730   |4294967294 |0       |0.49751243         |1            |1498590615       |
|76561198262712089|730   |4294967294 |2       |0.52380955         |1            |1451712030       |
+-----------------+------+-----------+--------+-------------------+-------------+-----------------+
only showing top 10 rows


======================================================================
votes_funny_exact_uint32_max
======================================================================
Violation count: 1511
Violation percentage: 1.3267700101964601e-05
Showing first 10 rows:
+-----------------+------+-----------+--------+-------------------+-------------+-----------------+
|author_steamid   |appid |votes_funny|votes_up|weighted_vote_score|comment_count|timestamp_created|
+-----------------+------+-----------+--------+-------------------+-------------+-----------------+
|76561198077137629|95400 |4294967295 |1       |0.50248754         |2            |1498924420       |
|76561198373834172|730   |4294967295 |3       |0.5497954          |0            |1491126049       |
|76561198135433836|730   |4294967295 |1       |0.5217391          |0            |1469723618       |
|76561198348454517|730   |4294967295 |2       |0.5217391          |1            |1491056634       |
|76561198098343581|730   |4294967295 |1       |0.50083196         |0            |1446364240       |
|76561197960572548|730   |4294967295 |1       |0.50248754         |0            |1490927311       |
|76561198249225048|730   |4294967295 |1       |0.50248754         |0            |1468877540       |
|76561198115233393|730   |4294967295 |1       |0.51008064         |0            |1490860377       |
|76561198363338932|575720|4294967295 |3       |0.49659863         |0            |1498450938       |
|76561198251991710|730   |4294967295 |0       |0.47826087         |0            |1490834417       |
+-----------------+------+-----------+--------+-------------------+-------------+-----------------+
only showing top 10 rows


======================================================================
Largest non-artifact votes_funny value below threshold
======================================================================
1699020607
39.55840616011024

## Noise

In [7]:
## Noises are values that are valid but possibly not useful & unstable

# 1. Check for columns with mostly zeros
noise_report(df, ROW_COUNT).show(truncate=False)

+------------------------------+-------------------+---------+--------------------+
|column_name                   |zero_or_false_count|row_count|zero_or_false_rate  |
+------------------------------+-------------------+---------+--------------------+
|comment_count                 |107639931          |113885601|0.9451583874944823  |
|author_playtime_last_two_weeks|100949251          |113885601|0.8864092573037394  |
|votes_funny                   |97979357           |113885601|0.8603313864059075  |
|votes_up                      |77654621           |113885601|0.6818651376305245  |
|weighted_vote_score           |73910148           |113885601|0.6489858889184771  |
|author_num_games_owned        |56725784           |113885601|0.49809443425600397 |
|author_playtime_at_review     |1871739            |113885601|0.016435255937227746|
|author_playtime_forever       |1736863            |113885601|0.015250944673857408|
|author_num_reviews            |634                |113885601|5.566989983220091E-6|
+------------------------------+-------------------+---------+--------------------+

## Uniqueness & Duplicates

In [13]:
## Uniqueness of catgorical features tells us insight of categories, while for numerical features,
## it indicates potential few_unique_values_per_column issue or possibility for discretization to a categorical type

# 1. Numbers of unique values for categorical/numerical & ID columns
uniqueness_report(df, ROW_COUNT).show(truncate=False)

## Duplicate tells us how many rows has exact duplicates and how frequent would a user to review the same game

# 2. Numbers of duplicate found in dataframe
# 3. Does the same user appear to have created multiple review records for the same game at the same time?
# 4. Inspect more details ("author_steamid", "appid", "timestamp_created") regarding instances in #3
# 5. Print out the duplicate reviews
dup_reports = duplicate_report(df, ROW_COUNT)
for (report, df) in zip(dup_reports['summary_rows'], dup_reports['issue_dfs'].values()):
    print_section(report['issue_name'])
    for name, val in report.items():
        if name == 'issue_name': continue
        print(f"{name}: {val}")
    df.show(n=5, truncate=False)
         
# 6. Create report on metadata difference on same (author ID, game ID, review date created)
# UN-ACHIEVE-ABLE; reason: too much join, putting too pressure on spark worker memory

+------------------------------+--------+---------------------+
|column_name                   |n_unique|unique_rate          |
+------------------------------+--------+---------------------+
|voted_up                      |2       |1.7561482596908805E-8|
|written_during_early_access   |2       |1.7561482596908805E-8|
|author_num_reviews            |1334    |1.1713508892138172E-5|
|author_num_games_owned        |9810    |8.613907213783769E-5 |
|author_playtime_last_two_weeks|19931   |1.750089548194947E-4 |
|comment_count                 |320438  |0.0028136831801941317|
|author_playtime_at_review     |359479  |0.00315649210122709  |
|votes_funny                   |493936  |0.004337124233993374 |
|author_playtime_forever       |544273  |0.004779120408733673 |
|votes_up                      |643808  |0.005653111493875332 |
|weighted_vote_score           |5979642 |0.05250568945937248  |
+------------------------------+--------+---------------------+


======================================================================
exact_dup
======================================================================
row_count: 113885601
distinct_full_rows: 113883499
exact_duplicate_rows: 2102
exact_duplicate_rate: 1.8457118209351155e-05
+-----------------+------+----------------------+------------------+-----------------------+------------------------------+-------------------------+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------+-----------+-------------------+-------------+---------------------------+---------+-----------------+-----------------+-----+
|author_steamid   |appid |author_num_games_owned|author_num_reviews|author_playtime_forever|author_playtime_last_two_weeks|author_playtime_at_review|author_last_played|review                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |voted_up|votes_up|votes_funny|weighted_vote_score|comment_count|written_during_early_access|language |timestamp_created|timestamp_updated|count|
+-----------------+------+----------------------+------------------+-----------------------+------------------------------+-------------------------+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------+-----------+-------------------+-------------+---------------------------+---------+-----------------+-----------------+-----+
|NULL             |NULL  |NULL                  |NULL              |NULL                   |NULL                          |NULL                     |NULL              |NULL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |NULL    |NULL    |NULL       |NULL               |NULL         |NULL                       |NULL     |NULL             |NULL             |1129 |
|76561198168773491|304050|0                     |1                 |447                    |0                             |194                      |1437419272        |Melhor jogo do mundo (para quem gosta de filas da disney)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |false   |0       |0          |0.0                |0            |false                      |brazilian|1436909003       |1436909003       |16   |
|76561198067677629|113420|141                   |44                |2066                   |0                             |2004                     |1569601756        |I played it. Got renamed to a ridiculous name because my name offended the you know who. Then the same mod who had renamed me popped up in main chat to ask people to keep the discussion to game related Q&A. I wasnt even chatting at the time, and the people who were were simply chit chatting. Apparently this is too much for this concentration camp of a game. No fun allowed. Only talk about the game.  I fucking hate this shit. Burn down every game company that manages its users like stupid cattle. God forbid giving personal details or talking about fun stuff. It might create you know, DISCUSSION. We dont want that. We want stupid morons who only talk about the game and pay their dues. Die. Eat it and die.|false   |0       |0          |0.48974463         |0            |false                      |english  |1434917837       |1434917837       |12   |
|76561198146250120|239030|0                     |1                 |1742                   |0                             |844                      |1656763710        |"""Arstotzka so great                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |NULL    |NULL    |NULL       |NULL               |NULL         |NULL                       |english  |NULL             |NULL             |12   |
|76561198039576815|278080|91                    |3                 |65                     |0                             |10                       |1466812029        |Does not support xbox 360 controller. Gave up after an hour trying to configure it.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |false   |0       |0          |0.4951857          |0            |false                      |english  |1421635697       |1421635697       |10   |
+-----------------+------+----------------------+------------------+-----------------------+------------------------------+-------------------------+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+--------+-----------+-------------------+-------------+---------------------------+---------+-----------------+-----------------+-----+
only showing top 5 rows


======================================================================
combo_dup
======================================================================
key_cols: ['author_steamid', 'appid', 'timestamp_created']
duplicate_key_groups: 770
duplicate_key_rows: 4085
+-----------------+-------+-----------------+-----+
|author_steamid   |appid  |timestamp_created|count|
+-----------------+-------+-----------------+-----+
|NULL             |NULL   |NULL             |1134 |
|NULL             |2348100|NULL             |582  |
|NULL             |2264930|NULL             |40   |
|NULL             |NULL   |0                |33   |
|76561198067677629|113420 |1434917837       |27   |
+-----------------+-------+-----------------+-----+
only showing top 5 rows

In [ ]:
spark.stop()